name: test

env:
  PROJECT_NAME: css430_template

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: docker
    container:
      image: pisanuw/uwb430
      options: --user root
    permissions:
      contents: read
    steps:
      - name: Install NodeJS Reps
        run: curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
      - name: Install NodeJS
        run: sudo yum install -y nsolid
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v5
        with:
          submodules: recursive
      - name: Create Build Directory
        run: mkdir -p build && mkdir -p run
      - name: Build
        run: cmake .. && cmake --build .
        working-directory: build
      - name: Run Tests
        run: ../build/${{ env.PROJECT_NAME }}-test
        working-directory: run
      - name: Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ../build/${{ env.PROJECT_NAME }}-test
        working-directory: run
